---

- name: Ensure a clone of rhel10 template with id 999
  community.general.proxmox_kvm:
    node: heimdall
    api_user: root@pam
    api_password: "{{ heimdall_root }}"
    api_host: heimdall.digitalpimp.nl
    clone: rhel10
    full: true
    storage: "{{ StorageVar }}"
    name: "{{ HostnameVar }}"

...
