---

- name: Create a new clone of rhel10 template with id 999
  community.general.proxmox_kvm:
    node: hera
    api_user: root@pam
    api_password: "{{ hera_root }}"
    api_host: hera.doctert.net
    clone: rhel10
    full: true
    storage: local-zfs
    name: "{{ HostNameVar }}"
  when: inventory_hostname == "hera"


...
